package com.starpy.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.starpy.sql.bean.StarpyPersion;

import com.starpy.sql.StarpyPersionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig starpyPersionDaoConfig;

    private final StarpyPersionDao starpyPersionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        starpyPersionDaoConfig = daoConfigMap.get(StarpyPersionDao.class).clone();
        starpyPersionDaoConfig.initIdentityScope(type);

        starpyPersionDao = new StarpyPersionDao(starpyPersionDaoConfig, this);

        registerDao(StarpyPersion.class, starpyPersionDao);
    }
    
    public void clear() {
        starpyPersionDaoConfig.clearIdentityScope();
    }

    public StarpyPersionDao getStarpyPersionDao() {
        return starpyPersionDao;
    }

}
